language: android
sudo: false
jdk: oraclejdk7
env:
  matrix:
  - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a armeabi
android:
  components:
  - platform-tools
  - build-tools-21.1.2
  - android-L
  - extra