language: android
sudo: false
jdk: oraclejdk7
env:
  matrix:
  - ANDROID_TARGET=android-L  ANDROID_ABI=armeabi-v7a armeabi
android:
  components:
  - platform-tools
  - build-tools-23.0.1
  - android-L
  - extra
  script:
  - ./gradlew :app:assembleRelease
before_install:
- openssl aes-256-cbc -K $encrypted_b4b4a3ef4d53_key -iv $encrypted_b4b4a3ef4d53_iv
  -in apk_key.jks.enc -out apk_key.jks -d
- chmod +x gradlew
